name: Build release-tags

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  bake-latest:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Get Latest Duo Auth Proxy Version
        id: getLatest
        shell: pwsh
        run: |
          $DuoAuthProxySrc = Invoke-WebRequest -Method HEAD -Uri "https://dl.duosecurity.com/duoauthproxy-latest-src.tgz"
          $DuoAuthProxySrc.Headers.'Content-Disposition'[0] -match '^attachment; filename=\"duoauthproxy-(.*)-src.tgz\"$'
          $DuoAuthProxyLatestVersion = $Matches[1]
          Write-Output "DuoLatestVersion=$($DuoAuthProxyLatestVersion)" | Out-File -FilePath $ENV:GITHUB_ENV -Encoding utf8 -Append
          Write-Host $DuoAuthProxyLatestVersion
      - name: Get Latest Package/Docker Container Version
        run: |
          manifest=$(curl -X GET https://docker.pkg.github.com/v2/TehMuffinMoo/duoauthproxy/latest/manifests/$GITHUB_SHA -u $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }} | jq '.')
          echo "manifest=$manifest" >> "$GITHUB_ENV"
#      - name: Checkout
#        uses: actions/checkout@v2.3.4
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#          platforms: all
#        with:
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1.6.0
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v1.10.0
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Build
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          file: ./Docker/Dockerfile
#          push: true
#          tags: ghcr.io/tehmuffinmoo/duoauthproxy:latest
#          build-args: |
#            BUILD_COMMIT=${{ github.sha }}
#            BUILD_BRANCH=${{ github.ref_name }}
